spring.profiles.active=prod
# spring.profiles.active=prod
spring.application.name=TaskSmasherBack

# DataSource
# ドライバーの設定
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# データベースへの接続URLを設定
spring.datasource.url=jdbc:mysql://localhost:3306/springdb?serverTimezone=Asia/Tokyo&amp
#spring.datasource.url=jdbc:mysql://db:3306/springdb?serverTimezone=Asia/Tokyo&amp
#;characterEncoding=UTF-8
# データベース接続のためのユーザー名を設定
spring.datasource.username=springuser
# データベース接続のためのパスワードを設定
spring.datasource.password=p@ss
# SQLスクリプトの初期化モードを設定
spring.sql.init.mode=always
# Log表示設定
logging.level.task_smasher.repository=DEBUG



## DataSource
## Postgresのドライバーの設定
#spring.datasource.driver-class-name=org.postgresql.Driver
## データベースへの接続URLを設定
#spring.datasource.url=jdbc:postgresql://localhost:5432/springdb
## データベース接続のためのユーザー名を設定
#spring.datasource.username=springuser
## データベース接続のためのパスワードを設定
#spring.datasource.password=p@ss
## SQLスクリプトの初期化モードを設定
#spring.sql.init.mode=always
## Log表示設定
#logging.level.com.example.webapp.repository=DEBUG


